# This is a basic workflow to help you get started with Actions

name: Deno Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [1.2.0, 1.2.1, 1.2.2]

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Build Deno Module
        run: deno run --reload --unstable --allow-net mod.ts
      - name: Test Deno Module
        run: deno test --unstable --allow-net
